apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base

patchesStrategicMerge:
  - |-
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: config-domain
      namespace: knative-serving
    data:
      <kubeflow_platform_url>: ""
      $patch: replace
  - |-
    apiVersion: v1
    kind: Secret
    metadata:
      name: kfs-secret
      namespace: serving
      annotations:
        serving.kubeflow.org/s3-endpoint: s3.eu-central-1.amazonaws.com
        serving.kubeflow.org/s3-usehttps: "1"
        serving.kubeflow.org/s3-verifyssl: "1"
        serving.kubeflow.org/s3-region: eu-central-1
    type: Opaque
    stringData: # use `stringData` for raw credential string or `data` for base64 encoded string
      AWS_ACCESS_KEY_ID: <ACCESS_KEY_ID>
      AWS_SECRET_ACCESS_KEY: '<SECRET_KEY_ID'
    ---
    apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: kfs-sa
      namespace: serving
    imagePullSecrets:
    - name: regcred
    secrets:
    - name: kfs-secret
