apiVersion: v1
kind: ConfigMap
metadata:
  name: config-network
  namespace: knative-serving
  labels:
    serving.knative.dev/release: "v0.17.1"
data:
  domainTemplate: "{{.Name}}-{{.Namespace}}.{{.Domain}}"
