kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: serving
  name: kserve
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kserve-bind
  namespace: serving
subjects:
- kind: Group
  name: system:serviceaccounts
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: kserve
  apiGroup: rbac.authorization.k8s.io
