apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base

patchesStrategicMerge:
- |-
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: config-domain
    namespace: knative-serving
  data:
    <kubeflow_platform_url>: ""
    $patch: replace