#!/usr/bin/with-contenv bash
cd "${HOME}"
sudo chown -R jovyan:root ~/.local/share/jupyter
exec \
s6-setuidgid jovyan \
/opt/conda/bin/jupyter lab \
--notebook-dir="${HOME}" \
--ip=0.0.0.0 \
--no-browser \
--allow-root \
--port=8888 \
--ServerApp.token="" \
--ServerApp.password="" \
--ServerApp.allow_origin="*" \
--ServerApp.base_url="${NB_PREFIX}" \
--ServerApp.authenticate_prometheus=False
