---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: admin-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  mountOptions:
    - flock
  persistentVolumeReclaimPolicy: Recycle
  csi:
    driver: fsx.csi.aws.com
    volumeAttributes:
      dnsname: DIR_DNS_NAME
      mountname: MOUNT_NAME
    volumeHandle: FSX_ID:/admin-pv/
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
  name: admin-pvc
  namespace: admin
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: admin-pv
---
apiVersion: batch/v1
kind: Job
metadata:
  name: perms
  namespace: admin
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      initContainers:
        - name: init-chown
          image: alpine
          args:
            - /bin/sh
            - -c
            - chown -R 1000:0 /home/jovyan
          volumeMounts:
            - mountPath: /home/jovyan
              name: persistent-storage
        - name: init-chmod
          image: alpine
          args:
            - /bin/sh
            - -c
            - chmod 775 /home/jovyan
          volumeMounts:
            - mountPath: /home/jovyan
              name: persistent-storage
      containers:
        - name: pod
          image: alpine
          securityContext:
            runAsUser: 1000
          command: ["/bin/sh", "-c"]
          args:
            - |
              mkdir -p "/home/jovyan/home"
          volumeMounts:
            - mountPath: /home/jovyan
              name: persistent-storage
      volumes:
        - name: persistent-storage
          persistentVolumeClaim:
            claimName: admin-pvc
      imagePullSecrets:
        - name: regcred
      restartPolicy: OnFailure
  activeDeadlineSeconds: 120
---

